function [s1,s2,s3,s4] = gen_latextable(textfile)

addpath('../');

fileID = fopen(textfile);
filename = textscan(fileID,'%s');

num_file = size(filename{1},1);
trial = 50;
x = zeros(num_file,1);
avgtime = zeros(2,2,num_file);
avgiter = zeros(2,2,num_file);
sdtime = zeros(2,2,num_file);
sditer = zeros(2,2,num_file);

for ii=1:num_file

        load(filename{1}{ii});
        
        fprintf('loading %s \n',filename{1}{ii});
                
        x(ii) = result.n;
        
        if find(result.iter >= 100000)
            display('some trial hit maximum number of iterations');
        end
        
        % these measures are 2 x 2 matrices.
        avgtime(:,:,ii) = mean(result.time,3); 
%         avgtime(:,:,ii) = mean((result.time./60),3);    %mean of CPU time (min)
        avgiter(:,:,ii) = ceil(mean(result.iter,3));
        sdtime(:,:,ii) = std(result.time,0,3);
%         sdtime(:,:,ii) = std((result.time./60),0,3);    %sd of CPU time (min)
        sditer(:,:,ii) = ceil(std(result.iter,0,3));
        
        %generating string for table1
        mid_msg1{ii} =  sprintf('%d  & %.2f (%.2f)  & %.2f (%.2f) & %.2f (%.2f) &  %.2f (%.2f) \\\\ \n',...
                        x(ii),...
                        avgtime(1,1,ii),sdtime(1,1,ii),...
                        avgtime(1,2,ii),sdtime(1,2,ii),...
                        avgtime(2,1,ii),sdtime(2,1,ii),...
                        avgtime(2,2,ii),sdtime(2,2,ii));
        
                              
        %generating string for table2
        mid_msg2{ii} =  sprintf('%d  & %.2f (%.2f)  & %.2f (%.2f) & %.2f (%.2f) &  %.2f (%.2f) \\\\ \n',...
                        x(ii),...
                        avgtime(1,1,ii),sdtime(1,1,ii),...
                        avgtime(2,1,ii),sdtime(2,1,ii),...
                        avgtime(1,2,ii),sdtime(1,2,ii),...
                        avgtime(2,2,ii),sdtime(2,2,ii));        
        
                     
        %generating string for table3
        mid_msg3{ii} =  sprintf(' %d & %d (%d)  & %d (%d) & %d (%d) &  %d (%d) \\\\ \n',...
                        x(ii),...
                        avgiter(1,1,ii),sditer(1,1,ii),...
                        avgiter(1,2,ii),sditer(1,2,ii),...
                        avgiter(2,1,ii),sditer(2,1,ii),...
                        avgiter(2,2,ii),sditer(2,2,ii));        
        
                                
        %generating string for table4
        mid_msg4{ii} =  sprintf(' %d & %d (%d)  & %d (%d) & %d (%d) &  %d (%d) \\\\ \n',...
                        x(ii),...
                        avgiter(1,1,ii),sditer(1,1,ii),...
                        avgiter(2,1,ii),sditer(2,1,ii),...
                        avgiter(1,2,ii),sditer(1,2,ii),...
                        avgiter(2,2,ii),sditer(2,2,ii)); 
        
end

end_msg = sprintf(['\\hline \n',...
        '\\end{tabular} \n',...
        '\\label{} \n',...
        '\\end{table} \n']);    
    
%------------------------table1---------------------
start_msg = sprintf(['\\begin{table}[ht] \n',...
        '\\centering \n',...
        '\\caption{} \n',...
        '\\begin{tabular}{|l| c|c|c|c|} \n',...
        '\\hline \n',...
        '\\multirow{3}{*}{$n$}  & \\multicolumn{4}{|c|}{CPU time (seconds)}\\\\ \n',...
        '\\cline{2-5}',...
        '& \\multicolumn{2}{|c|}{small $\\lambda_{\\min}(S)$ & \\multicolumn{2}{|c|}{large $\\lambda_{\\min}(S)$ \\\\ \n',...
        '\\cline{2-5} \n',...
        '& $\\gamma_1$ & $\\gamma_2$ & $\\gamma_1$ & $\\gamma_2$ \\\\ \n',...
        '\\hline \n']);     
s1 = sprintf(['%s','%s','%s'],start_msg,mid_msg1{:},end_msg);

%------------------------table2---------------------
start_msg = sprintf(['\\begin{table}[ht] \n',...
        '\\centering \n',...
        '\\caption{} \n',...
        '\\begin{tabular}{|l| c|c|c|c|} \n',...
        '\\hline \n',...
        '\\multirow{3}{*}{$n$}  & \\multicolumn{4}{|c|}{CPU time (seconds)}\\\\ \n',...
        '\\cline{2-5} \n',...
        '& \\multicolumn{2}{|c|}{$\\gamma = 0.05\\gamma_{\\mathrm{max}}$} & \\multicolumn{2}{|c|}{$\\gamma = 0.8\\gamma_{\\mathrm{max}}$}\\\\ \n',...
        '\\cline{2-5} \n',...
        '& small $\\lambda_{\\min}(S)$ & large $\\lambda_{\\min}(S)$ & small $\\lambda_{\\min}(S)$  &large $\\lambda_{\\min}(S)$ \\\\ \n',...
        '\\hline \n']);           
s2 = sprintf(['%s','%s','%s'],start_msg,mid_msg2{:},end_msg); 

%------------------------table3---------------------
start_msg = sprintf(['\\begin{table}[ht] \n',...
        '\\centering \n',...
        '\\caption{} \n',...
        '\\begin{tabular}{|l| c|c|c|c|} \n',...
        '\\hline \n',...
        '\\multirow{3}{*}{$n$}  & \\multicolumn{4}{|c|}{Number of iterations}\\\\ \n',...
        '\\cline{2-5}',...
        '& \\multicolumn{2}{|c|}{small $\\lambda_{\\min(S)$} & \\multicolumn{2}{|c|}{large $\\lambda_{\\min(S)}\\\\ \n',...
        '\\cline{2-5} \n',...
        '& $\\gamma_1$ & $\\gamma_2$ & $\\gamma_1$ & $\\gamma_2$ \\\\ \n',...
        '\\hline \n']);
s3 = sprintf(['%s','%s','%s'],start_msg,mid_msg3{:},end_msg); 

%------------------------table4---------------------
start_msg = sprintf(['\\begin{table}[ht] \n',...
        '\\centering \n',...
        '\\caption{} \n',...
        '\\begin{tabular}{|l| c|c|c|c|} \n',...
        '\\hline \n',...
        '\\multirow{3}{*}{$n$}  & \\multicolumn{4}{|c|}{Number of iterations}\\\\ \n',...
        '\\cline{2-5} \n',...
        '& \\multicolumn{2}{|c|}{$\\gamma = 0.05\\gamma_{\\mathrm{max}}$} & \\multicolumn{2}{|c|}{$\\gamma = 0.8\\gamma_{\\mathrm{max}}$}\\\\ \n',...
        '\\cline{2-5} \n',...
        '& small $\\lambda_{\\min}(S)$ & large $\\lambda_{\\min}(S)$ & small $\\lambda_{\\min}(S)$  &large $\\lambda_{\\min}(S)$ \\\\ \n',...
        '\\hline \n']);
s4 = sprintf(['%s','%s','%s'],start_msg,mid_msg4{:},end_msg); 
end